### ISSUE TITLE
Missing Source Code for Twin Service Event Dispatcher and Event Store Dispatcher

### ISSUE THREAD

**Issue by ZzcChen** [Open-Digital-Twin/ktwin-article#1]
**Description**: I noticed that the architecture diagram indicates the presence of a **Twin Service Event Dispatcher** and an **Event Store Dispatcher** as critical components of the system. However, I couldn't find their source code in this repository or any references explaining their implementation or deployment.

**Request**:
1. Could you confirm if these dispatchers are missing, or if they exist in a separate repository that hasn’t been linked?
2. If they don’t exist yet, could you consider adding their implementation (or at least a specification/placeholder) to the repository to help contributors understand the flow and functionality better?
3. If they are intentionally omitted, could you provide guidance on how to implement these dispatchers or clarify their expected functionality and deployment?

**Comment by agwermann** [comment]
@ZzcChen, thanks for your interest in testing KTWIN.

You can install the **Event Store Dispatcher** and **MQTT Dispatcher** following the [Installation Steps](https://github.com/Open-Digital-Twin/ktwin-operator/blob/main/docs/Install.md#install-resources-in-kubernetes). KTWIN Operator should automatically create them once you apply the custom resources to the cluster. The **Twin Service Event Dispatchers** are created once you define a TwinInterface/TwinInstance to the cluster: it should created the dispatcher along with your application container.

Their source code of KTWIN dispatchers is available [here](https://github.com/Open-Digital-Twin/ktwin-dispatchers).
Their containers of KTWIN dispatchers are available [here](https://github.com/orgs/Open-Digital-Twin/packages?tab=packages&q=dispatcher).

**Comment by ZzcChen** [comment]
Thank you for your help and for providing the detailed information. I’ll review the new installation steps, and if I have any questions, I hope it’s okay to reach out to you again. Thanks once more for your assistance!

**Comment by ZzcChen** [comment]
Hi @agwermann 

Thank you for the detailed explanation and links provided earlier. To better understand the configuration process, could you let me know where I might find a specific example of a TwinInterface or TwinInstance custom resource? If examples aren't available directly, is there any documentation or repository section you’d recommend for better understanding how to define these resources?

I appreciate your assistance and look forward to your response.

**Comment by agwermann** [comment]
@ZzcChen, please refer to [these](https://github.com/Open-Digital-Twin/ktwin-smart-cities-dtd/tree/main/usecases/nyc) TwinInstances and TwinInterfaces examples.

**Comment by ZzcChen** [comment]
Hi @agwermann 
Thank you for sharing the examples of TwinInstances and TwinInterfaces. I’ll review them thoroughly and reach out if I have any further questions. Your assistance is greatly appreciated!

**Comment by ZzcChen** [comment]
Hi @agwermann,

Sorry to bother you again. I'm currently facing an issue where messages sent by the broker ingress to the RabbitMQ exchange are not being routed to the `cloud-event-dispatcher-queue`.

After investigation, I found that the problem is related to the header matching rules defined in the queue bindings, specifically:
* `eventing.knative.dev/trigger`: `ngsi-ld-city-device`
* `ktwin/twin-interface`: `ngsi-ld-city-device`

It seems that these headers are not being correctly added or matched, which prevents the message from being routed to the queue. While the broker ingress successfully sends the message to the exchange, it doesn’t reach the queue.

Could you advise if there might be an issue in how I configured or ran the Ktwin setup? Any guidance on resolving this would be greatly appreciated.

Thank you!

![image](https://github.com/user-attachments/assets/246840f8-24c0-4764-8949-a2d03431bd4d)

**Comment by agwermann** [comment]
@ZzcChen thanks for sharing the above scenario.
I have applied a code fix for this issue. You can deploy the latest operator version and you will no longer see those extra routing rules in the cloud event dispatcher binding.

```sh
make deploy IMG=ghcr.io/open-digital-twin/ktwin-operator@sha256:0ff3ae893e090370b1b0ec689dabe06df6bd112d3940c0215892ae4373e6f21e
```

**Comment by ZzcChen** [comment]
Thank you for addressing the issue and providing the fix. I'll deploy the latest operator version and confirm the results. Appreciate your support!

**Comment by emeresHub** [comment]
Hi @agwermann, sorry to bother but I have some issues with deploying the twin interface and intstances of some of the services in the `nyc/1-neighbourhood`.

While deploying the `ngsi-ld-city-streetlight` twin interface and its associated instances and relationships, I encountered the following error in the logs for the `ngsi-ld-city-streetlight-00001-deployment`:

```
"Error processing cloud event request","error":"Get \"/api/v1/twin-events/ngsi-ld-city-streetlight/ngsi-ld-city-streetlight-nb001-sl00001/latest\": unsupported protocol scheme \"\""
```

#### **Steps to Reproduce**
1. Deployed the twin interface `ngsi-ld-city-streetlight` as described in the provided `1-Streetlight-Interface.yaml`.
2. Created instances for the Streetlight twin and its dependencies:
   - Streetlight instance: `ngsi-ld-city-streetlight-nb001-sl00001`
   - Device instance: `ngsi-ld-city-device-nb001-sl00001`
   - Streetlight group: `ngsi-ld-city-streetlightgroup-nb001-sl00001`
   - Streetlight control cabinet: `ngsi-ld-city-streetlightcontrolcabinet-nb001-sl00001`
   - Streetlight model: `ngsi-ld-city-streetlightmodel-nb001-sl00001`
3. Verified the logs of the deployment `ngsi-ld-city-streetlight-00001-deployment` after the deployment.

#### **Expected Behavior**
The service should handle cloud events properly by constructing a valid HTTP URL with the correct protocol scheme (e.g., `http://` or `https://`) for the API request to `/api/v1/twin-events/...`.

#### **Actual Behavior**
The service logs indicate that the protocol scheme is missing in the constructed API URL, resulting in the following error:
```
Error processing cloud event request","error":"Get \"/api/v1/twin-events/ngsi-ld-city-streetlight/ngsi-ld-city-streetlight-nb001-sl00001/latest\": unsupported protocol scheme \"\""
```

#### **Code/Configuration Details**

In addition to the `Streetlight` twin interface, I created twin instances for the following components:

**1. Streetlight Control Cabinet**
```yaml
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-streetlightcontrolcabinet-nb001-sl00001
  namespace: ktwin
spec:
  interface: ngsi-ld-city-streetlightcontrolcabinet
  twinInstanceRelationships:
  - name: refStreetlightGroup
    instance: ngsi-ld-city-streetlightgroup-nb001-sl00001
    interface: ngsi-ld-city-streetlightgroup
  - name: refDevice
    instance: ngsi-ld-city-device-nb001-sl00001
    interface: ngsi-ld-city-device
status: {}
```

**2. Streetlight Group**
```yaml
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-streetlightgroup-nb001-sl00001
  namespace: ktwin
spec:
  interface: ngsi-ld-city-streetlightgroup
  twinInstanceRelationships:
  - name: refStreetLight
    instance: ngsi-ld-city-streetlight-nb001-sl00001
    interface: ngsi-ld-city-streetlight
  - name: refStreetlightControlCabinet
    instance: ngsi-ld-city-streetlightcontrolcabinet-nb001-sl00001
    interface: ngsi-ld-city-streetlightcontrolcabinet
status: {}
```

**3. Streetlight Model**
```yaml
apiVersion: dtd.ktwin/v0
kind: TwinInstance
metadata:
  name: ngsi-ld-city-streetlightmodel-nb001-sl00001
  namespace: ktwin
spec:
  interface: ngsi-ld-city-streetlightmodel
status: {}
```

#### **Logs**
Relevant log snippet:
```
"Error processing cloud event request","error":"Get \"/api/v1/twin-events/ngsi-ld-city-streetlight/ngsi-ld-city-streetlight-nb001-sl00001/latest\": unsupported protocol scheme \"\""
```

#### **Potential Cause**
The error indicates that the service is attempting to construct a URL without specifying the protocol scheme (e.g., `http://` or `https://`). This is likely due to:
- Missing or misconfigured base URL in the environment variables or configuration.
- Code constructing the URL does not properly prepend the protocol scheme.


#### **NOTE:**
This issue is not limited to the `streetlight` deployment; similar errors occur with other `dtd` deployments, including `traffic-flow`, `parking-spot`, `crowd-flow`, `air-quality`, and `weather`. However, the `battery-device` deployment works without issues, suggesting a potential inconsistency across deployments. 

Could this be investigated to identify and resolve the root cause? Thank you!
